site_name: FastAPI Utilities
site_description: FastAPI utilities
site_url: https://fastapi-utils.davidmontague.xyz/

theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'orange'
  logo: 'img/icon-white.svg'
  favicon: 'img/favicon.png'

repo_name: dmontagu/fastapi-utils
repo_url: https://github.com/dmontagu/fastapi-utils

nav:
  - FastAPI Utilities: 'index.md'
  - User Guide:
      - Class Resource: 'user-guide/class-resource.md'
      - Class Based Views: 'user-guide/class-based-views.md'
      - Repeated Tasks: 'user-guide/repeated-tasks.md'
      - Timing Middleware: 'user-guide/timing-middleware.md'
      - SQLAlchemy Sessions: 'user-guide/session.md'
      - OpenAPI Spec Simplification: 'user-guide/openapi.md'
      - Other Utilities:
          - APIModel: 'user-guide/basics/api-model.md'
          - APISettings: 'user-guide/basics/api-settings.md'
          - String-Valued Enums: 'user-guide/basics/enums.md'
          - CamelCase Conversion: 'user-guide/basics/camelcase.md'
          - GUID Type: 'user-guide/basics/guid-type.md'
  - Get Help: 'help-fastapi-utils.md'
  - Development - Contributing: 'contributing.md'
  - Release Notes: 'release-notes.md'

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - tables
  - smarty

extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/dmontagu/fastapi-utils'

extra_css:
  - 'css/custom.css'
